[package]
name = "csv2jsonl"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Convert CSV files to JSONL"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
csv = "1.3.1"
indicatif = "0.17.9"
serde = "1.0.215"
serde_json = "1.0.133"
